name: Falkor CI - Develop

on:
  workflow_dispatch:
  schedule:
    - cron: "40 3 * * *" # 3:40am UTC
  pull_request:
    branches:
      - develop

jobs:
  CId:
    name: Develop CI Suite

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Npm Dependencies
        run: |-
          npm install --ignore-scripts --fund false

      - name: Lint Project
        run: |-
          npm run lint

      - name: Bundle Project
        run: |-
          npm run release

      - name: Use Pandoc v3.1
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: "3.1"

      - name: Build Manual
        run: |-
          npm run man

      - name: Install Project Globally
        run: |-
          npm install --global --fund false .

      - name: Get Executable Version
        run: |-
          falkor-commander --version

      - name: Get Executable Hep
        run: |-
          falkor-commander --help

      - name: Get Executable Manual
        run: |-
          man falkor-commander | col -bx
