name: Falkor CI - Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CIr:
    name: Release CI Suite

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Npm Dependencies
        run: |-
          npm clean-install --ignore-scripts

      # - name: Install Npm Peer Dependencies (for npm v6)
      #   if: ${{ matrix.node-version == '14.x' }}
      #   run: |-
      #     npm install <package-names> --no-save

      - name: Lint Project
        run: |-
          npm run lint

      - name: Bundle Project
        run: |-
          npm run release

      - name: Use Pandoc v2.18
        if: ${{ matrix.os != 'windows-latest' }}
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: "2.18"

      - name: Build Manual
        if: ${{ matrix.os != 'windows-latest' }}
        run: |-
          npm run man

      - name: Install Project Globally
        run: |-
          npm install --global .

      - name: Get Executable Version
        run: |-
          falkor-commander --version

      - name: Get Executable Hep
        run: |-
          falkor-commander --help

      - name: Get Executable Manual
        if: ${{ matrix.os != 'windows-latest' }}
        run: |-
          man falkor-commander | col -bx
